image: fabrizzio/docker-php-ci
script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction
  - vendor/bin/phpunit
notify:
  email:
    recipients:
      - contact@dieterprovoost.be
